### ISSUE TITLE
Potential Exposed Credentials in URI

### ISSUE THREAD

**Issue by KabirKwatra** [cn-cerc/summer-framework#14]
Potential security breach. See https://github.com/cn-cerc/summer-framework/blob/6c16f771d4f331fb309fca952189b36f1c78140c/summer-db/src/main/java/cn/cerc/db/mongo/MongoConnection.java#L62

**Comment by HuangRongjun** [comment]
Thank You Very Much！

**Comment by HuangRongjun** [comment]
see this [link](https://github.com/cn-cerc/summer-framework/commit/ed48e9ed3a898311b62e33719b158c0a9d63f05b)
